### ISSUE TITLE
Uncaught TypeError: Cannot read property '4' of null

### ISSUE THREAD

**Issue by akoskm** [kai5z/BeamTrace2D#1]
In some rare cases the algorithm returns with the following error:

```
Uncaught TypeError: Cannot read property '4' of null
```

on line 403.

Looking at the `lineIntersection` function which usually returns an array, looks like in these special cases it exists with:

```
        denominator = ((y22 - y21) * (x12 - x11)) - ((x22 - x21) * (y12 - y11));
        if (denominator == 0) {
            return null;
        }
```

I don't know why though. I'll try to give the steps to reproduce the problem but I feel that this happens only on specific source/listener coordinates and it will be pretty hard to tell where those are.

It also won't help much but here is the screenshot which I took right after the error occurred. I already moved the source and the listener but they were in that part of the polygon.

![bt2derror](https://cloud.githubusercontent.com/assets/3111627/16485668/77c22e42-3ec0-11e6-954d-72e292b5e8f1.png)

**Comment by kai5z** [comment]
Thanks for finding the problem. Should be fixed now, at least that specific error message shouldn't appear.

**Comment by akoskm** [comment]
Hello Kai, thanks for the quick response! I think this was one of the first things I tried. This indeed prevents the error from showing up it but doesn't solve the problem and you still can't do the beam trace from that specific source and listener location.

In other words, if you set the source and listener to the same x, y coordinates again, nothing will happen.

I'll try to put together a test case to prove this, stay tuned! 😃

**Comment by akoskm** [comment]
@kai5z can we reopen this issue? The change you committed breaks even the `index.html` example. On all places in your code you expect the return value of `lineIntersection` to be an array or null. I reverted these changes and started to work on a test which will hopefully reproduce the above error.

**Comment by kai5z** [comment]
Ah, great, thanks :) Didn't even test the solution, silly me. Please let me know when you have the test ready so we can fix the problem!

**Comment by akoskm** [comment]
@kai5z I figured out what lead to the TypeError I was seeing on your blog. That demo uses an older version of the script which doesn't have the additional check on line [403](https://github.com/kai5z/BeamTrace2D/blob/998fa8fd427be600dd058de32ee1b15c8f64d0e3/js/beamtrace2d.js#L403).

However, as I pointed out the changes you introduced in your previous two commits broke the app. I added a very basic test in https://github.com/kai5z/BeamTrace2D/commit/9a4db22b6508ce88c5c4cb574bf51c67074eaf11 which ensures that the `path_array` is properly generated, has the appropriate type and size.

Seems there isn't any bugs in the current code so I'm closing this.

Regarding the performance of the algorithm, I'll extend the current test suite with a wall layout which really slows down the algorithm, even if the resulting canvas doesn't have many beams at all.
